### ISSUE TITLE
Dev mode nonfunctional in IE11 due to socksjs error

### ISSUE THREAD

**Issue by richardtallent** [vuejs-templates/webpack#1208]
This template is not functioning in development mode on IE11. It loads and renders the app, then stops executing. If you go into F12 Tools, you see:

```
socksjs.js, line 4468
 parseSupported = !parse('"\t"');
Invalid character
```

Steps to reproduce:
1. Execute the following:
```bash
vue init webpack test
cd test
npm run dev
```
2. Open IE11
3. Open F12 Tools
4. Navigate tohttp://localhost:8080

I'm using the latest version of node and npm (just upgraded), and `webpack-dev-server` 2.9.7.

**Comment by LinusBorg** [comment]
Hm. Strange. No idea what's causing that tbh :/

**Comment by LinusBorg** [comment]
Was fixed with v2.10.1 of webpack-dev-server

**Comment by n3ps** [comment]
Using webpack-dev-server v3.1.5 and the error is still there

**Comment by macmonkey** [comment]
Same for me with v3.1.10.

**Comment by TiagoFuelber** [comment]
Same for v3.2.1 =/
