### ISSUE TITLE
e2e/nightwatch fails on Windows

### ISSUE THREAD

**Issue by phromo** [vuejs-templates/webpack#40]
`npm run e2e` fails on windows due to known windows limitations in node spawn (will not locate the generated nightwatch.cmd)

Resolve by using https://github.com/IndigoUnited/node-cross-spawn instead:

in `e2e/runner.js`
`var runner = require('cross-spawn').spawn('./node_modules/.bin/nightwatch',`

**Comment by yyx990803** [comment]
Fixed, thanks!

**Comment by jpokrzyk** [comment]
This still fails on windows with chrome. https://github.com/vuejs-templates/webpack/blob/master/template/test/e2e/nightwatch.conf.json#L12 needs a .exe after it.

@phromo I'm a little confused where to actually do a PR or report an issue. Nightwatch?

**Comment by yyx990803** [comment]
@jpokrzyk can you confirm adding `.exe` makes it work?

It'd be nice if Nightwatch can intelligently handle the correct extension on Windows, so it's worth opening an issue there. But in the meanwhile we should probably look for a way to make it work as-is.

**Comment by yyx990803** [comment]
Ok, this should do it - chromedriver's npm bin detects the correct platform handling: https://github.com/vuejs-templates/webpack/commit/0ccbc85bc09ab1a485f2eab4e6ed63516ca6acf9

**Comment by jpokrzyk** [comment]
@yyx990803 Nice find with 0ccbc85. I looked around for a chrome driver CMD before making my earlier comment and couldn't find it. I'm still pretty new to node and very new to npm. I should have looked harder ;)

This didn't completely resolve e2e on windows though. Now it just hangs when trying to launch the chrome driver. It looks like the js runner nightwatch uses internally uses regular spawn instead of cross-spawn like @phromo mentioned in the original post.

And to answer your earlier question: yes, if I just add the .exe to the end of "webdriver.chrome.driver": "node_modules/chromedriver/lib/chromedriver/chromedriver" everything works as expected. 

So now I should definitely raise an issue with nightwatch right? I'm surprised no one brought it up over there. I could find anything in their issue log or PRs. 

Thanks for providing all of this. Nightwatch looks pretty awesome.

**Comment by phromo** [comment]
@jpokrzyk nightwatch just passes the path on to java, so it's actually the call from java (inside selenium) that's not being called with a shell, thus not picking up the .cmd. For me, just changing the path in the conf works. I guess it should either be fixed in selenium or have nightwatch build a workaround (looking for the .cmd and passing that).

**Comment by yyx990803** [comment]
Let's see if this does it: https://github.com/vuejs-templates/webpack/commit/58c9d5c9710229c8c2cbe5a65b3744c842907044

**Comment by jpokrzyk** [comment]
Yea sweet. Completely working now.

**Comment by yyx990803** [comment]
:tada:
