### ISSUE TITLE
Multiple Promise libraries being exported in webpack

### ISSUE THREAD

**Issue by sudo-suhas** [vuejs-templates/webpack#532]
This issue was also discussed here - https://forum.vuejs.org/t/multiple-promise-libraries-being-exported-in-webpack/6610. My thanks to @LinusBorg 

## Setup

|Module|Version|
|----------|----------|
|Node.js|6.9.2|
|npm|4.3|
|vue-cli|2.8.1|
|vue|2.1.10|
|webpack|2.2.1|
|babel|6.22|

## Issue details
I have a modified version of the vue-js webpack template which I migrated to webpack 2(some time back) and also made other changes.
I have added [es6-promise](https://github.com/stefanpenner/es6-promise) for use with vuex as it needs a Promise library implementation. When I recently used [webpack-bundle-analyzer](https://github.com/th0r/webpack-bundle-analyzer), I saw this:

<img src="https://forum.vuejs.org/uploads/default/original/2X/c/cbd1a5768659b5168e148a2d76eb08b48edb4a4f.png" />

The promise library polyfill is being exported twice. From the discussion with Linus, we were able to conclude that this is happening due to [babel-plugin-transform-runtime](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime) which, among other things, also introduces polyfills for things like`Map` and `Promise`. [This section](https://github.com/babel/babel-loader#note-transform-runtime--custom-polyfills-eg-promise-library) from babel-loader README is quite relevant but I failed to solve the issue with the bootstrap suggested. Linus suggested that the babel config could be changed to not add polyfills by default:
```js
"plugins": [
  ["transform-runtime", { "polyfills": false}]
]
```
Are there any polyfills required by vue, vuex and vue-router? I will also try to get rid of the polyfills and check if something breaks.

**Comment by LinusBorg** [comment]
Vuex uses Promises, so those have to be polyfilled it one wants to support browsers that don't support them natively yet (read: IE <=11).

**Comment by simplesmiler** [comment]
A side note, [`es6-promise`](https://www.npmjs.com/package/es6-promise) and `es6.promise.js` from [`core-js`](https://www.npmjs.com/package/core-js) are different modules, it's not the same module exported twice.

**Comment by sudo-suhas** [comment]
I tested my app after removing the polyfills and things seem to be working fine. However, note that I am extensively using lodash and not relying on native modules.

**Comment by LinusBorg** [comment]
@simplesmiler Yeah we are aware of that.

@sudo most of the stuff that `tranform-runtime` would might polyfill (especially Promises) is available in modern browsers, but might fail in IE11 or even safari

**Comment by limichange** [comment]
@LinusBorg 
So, if we want to support most browsers, we need import the two promise polyfill ?

**Comment by LinusBorg** [comment]
No, that's not what I meant. What I mean is

If we remove the tranform-runtime (or deactivate the automatic polyfill feature it provides), then you, the developer, have to manually include those polyfills if you want to make your app work with out-of-date browsers.

I think we can counter-balance that by switching the `es2015` preset for `babel-preset-env`, especially [this feature](https://github.com/babel/babel-preset-env#usebuiltins) of that preset, so users can easily add the polyfills that their target browser needs. Maybe that could even be a new option in the setup process.

**Comment by limichange** [comment]
I agree it. `babel-preset-env` is better.
https://github.com/vuejs-templates/webpack/pull/501

**Comment by sudo-suhas** [comment]
Although this doesn't matter if `transform-runtime` is going to be removed, in a different project, the  `"polyfill": false` directive is not being respected. Could have something to do with [this](https://github.com/babel/babel/issues/4274) issue but I am not calling `super()` anywhere.

**Comment by sudo-suhas** [comment]
I extracted the stats for my webpack chunks and modules by enabling `profile` an using [this](https://www.npmjs.com/package/stats-webpack-plugin) plugin. Can anybody please help me understand why the `polyfill: false` directive is being ignored? The stats.json file can be uploaded [here](https://webpack.github.io/analyse/) for interactive visualization.
<details>
<summary>Babel config</summary>

```json
{
    "presets": [
        ["es2015", { "modules": false }],
        "stage-1"
    ],
    "plugins": [
        "lodash",
        "syntax-dynamic-import", [
            "component", [{
                "libraryName": "element-ui",
                "styleLibraryName": "theme-default"
            }]
        ],
        ["transform-runtime", { "polyfill": false }]
    ],
    "comments": false,
    "env": {
        "test": {
            "plugins": ["istanbul"]
        }
    }
}

```
</details>

Compressed stats file - [stats.json.zip](https://github.com/vuejs-templates/webpack/files/800989/stats.json.zip)

**Comment by LinusBorg** [comment]
@sudo-suhas 

the ignore `polyfill: false` option should be fixed in babel since March, according to the issue you linked.

But I'm not sure the underlying issue is resolved. we switched to `babel-preset-env`, but still use `transfrom-runtime`. 

TBH I simply haven't looked into this for months and am not 100% sure what's going on under the hood right now concerning polyfills.

Do you have any further results you can share?

**Comment by sudo-suhas** [comment]
@LinusBorg My understanding was that it was fixed in babel `7.0` which is still in beta. I will check this again sometime this week.

**Comment by sudo-suhas** [comment]
Apologies for the delay in my response. I tried this out with the latest beta version for babel packages and the issue is not fixed. I have requested that the issue in babel repo be reopened.
