### ISSUE TITLE
When i use vue-router's lazy-loading, IE11 will give an error 'Promise Undefined'.

### ISSUE THREAD

**Issue by resyin** [vuejs-templates/webpack#724]
When i use vue-router's lazy-loading, IE11 will give an error 'Promise Undefined'.

my code:

```
// src/router/index.js
import Vue from 'vue'
import Router from 'vue-router'
Vue.use(Router)
export default new Router({
  routes: [
    {
      path: '/',
      redirect: '/home'
    }, {
      path: '/home',
      component: resolve => require(['@/components/Hello'], resolve)
    }
  ]
})
```

I had installed `babel-polyfill`,and import it in the first line of main.js.

```
// src/main.js
import 'babel-polyfill'
import Vue from 'vue'
import App from './App'
import router from './router'
import store from './store'

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  template: '<App/>',
  components: {App}
})
```
the error is  `var resolvedPromise = new Promise(function(resolve) { resolve(); });` .
but polyfill not working. what's wrong with me?

my development environment:
- node@6.9.2
- vue-cli@2.8.1
- babel-polyfill@6.23.0
- vue@2.2.6
- vue-router@2.3.1

**Comment by resyin** [comment]
I upgraded the vue-cli yesterday. In my previous project (my first installation of vue-cli was probably in January of this year) , the same code is ok in IE11.😥

**Comment by lixuguang88** [comment]
I get the same error and  i use es6-promise,
error come from mainfest.js, but es6-promise in vendor.js

**Comment by resyin** [comment]
ooh! the problem have been solved when i `vue init webpack new-project`  today.🙀

**Comment by greenbayrocks** [comment]
This is still an issue.  Just created mine this morning (`vue init webpack new-project`), using vue-cli 2.9.1.

**Comment by F1LT3R** [comment]
Have you tried using something like bluebird for your promises instead of IEs implantation? I have not tried this, but if it's something that is incorrectly implemented/unimplemented in IE causing the problem, it could help to try bluebird.
